project:
  type: website

website:
  title: "Tsepo's website"
  site-url: https://tsnkosi.netlify.app
  
  twitter-card: true
  
  favicon: assets/favicon.ico
  
  navbar:
    right:
      - text: Posts
        href: post/
      - text: Projects
        href: projects/
      - about.qmd
      - icon: github
        href: https://github.com/SmangaNkosi
      - text: BS
        href: https://bsky.app/profile/tseponkosi.bsky.social
        

format:
  html:
    # Theme
    theme:
      - lumen
      - custom.scss
    
    # Table of contents
    toc: true
    toc-title: "Contents"
    toc-location: left
    
    lang: en-ZA

editor: visual

